### ISSUE TITLE
No link to godot 3

### ISSUE THREAD

**Issue by Esnos33** [godotrecipes/audio_manager#1]
Hi, I was reading your tutorial : http://kidscancode.org/godot_recipes/3.x/audio/audio_manager/
but link doesn't work and this situation is the same for every other tutorial with .zip file. Are you planning to focus only on godot 4?

**Comment by cbscribe** [comment]
No, that was not intentional, but a side-effect of the re-organization to support 3 & 4. I fixed most links, but there are still a few I need to replace.

Thanks for the note!
